/**
 * Export Obsidian as a constant + namespace
 *
 * This allows working around the double-dynamic lookup penalty when using Obsidan
 * exports, by using `o.Whatever` instead of plain `Whatever`.  Paradoxically, the
 * latter is slower and adds more frames in the debugger, because esbuild wraps
 * re-exports as a dynamic lookup, *and* Obsidian's own bundler has a similar wrapping.
 * Using the `obsidian.` prefix gets rid of the dynamic lookups, making it easier to
 * step through code that's using it.
 *
*/
import { 
// autogenerated list from export-template.md - do not edit here
AbstractTextComponent, addIcon, apiVersion, App, arrayBufferToBase64, arrayBufferToHex, base64ToArrayBuffer, BaseComponent, ButtonComponent, ColorComponent, Component, debounce, DropdownComponent, EditableFileView, Editor, editorEditorField, editorInfoField, editorLivePreviewField, EditorSuggest, editorViewField, Events, ExtraButtonComponent, FileManager, FileSystemAdapter, FileView, finishRenderMath, fuzzySearch, FuzzySuggestModal, getAllTags, getBlobArrayBuffer, getIcon, getIconIds, getLinkpath, hexToArrayBuffer, HoverPopover, htmlToMarkdown, ItemView, iterateCacheRefs, iterateRefs, Keymap, livePreviewState, loadMathJax, loadMermaid, loadPdfJs, loadPrism, MarkdownEditView, MarkdownPreviewRenderer, MarkdownPreviewView, MarkdownRenderChild, MarkdownRenderer, MarkdownSourceView, MarkdownView, Menu, MenuItem, MenuSeparator, MetadataCache, Modal, moment, MomentFormatComponent, normalizePath, Notice, parseFrontMatterAliases, parseFrontMatterEntry, parseFrontMatterStringArray, parseFrontMatterTags, parseLinktext, parseYaml, Platform, Plugin, PluginSettingTab, PopoverState, PopoverSuggest, prepareFuzzySearch, prepareQuery, prepareSimpleSearch, removeIcon, renderMatches, renderMath, renderResults, request, requestUrl, requireApiVersion, resolveSubpath, sanitizeHTMLToDom, Scope, SearchComponent, setIcon, Setting, SettingTab, SliderComponent, sortSearchResults, stringifyYaml, stripHeading, stripHeadingForLink, SuggestModal, TAbstractFile, Tasks, TextAreaComponent, TextComponent, TextFileView, TFile, TFolder, ToggleComponent, ValueComponent, Vault, View, Workspace, WorkspaceContainer, WorkspaceFloating, WorkspaceItem, WorkspaceLeaf, WorkspaceMobileDrawer, WorkspaceParent, WorkspaceRibbon, WorkspaceRoot, WorkspaceSidedock, WorkspaceSplit, WorkspaceTabs, WorkspaceWindow, } from "obsidian";
export var obsidian;
(function (obsidian) {
    Object.assign(obsidian, require("obsidian"));
})(obsidian || (obsidian = {}));
